<a href="https://colab.research.google.com/github/sipocz/_earthQuake/blob/main/EarthQuaqe_Clustering_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
#EarthQuake
from google.colab import drive
drive.mount('/content/drive',force_remount=True)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import sweetviz as sw

#!pip install sweetviz
#import sweetviz as sw
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

Mounted at /content/drive


In [95]:
df=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/features_a.csv")
df_clasters=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/train_labels.csv")
df_testvalues=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/test_a.csv")

In [62]:
numx=110000
Y=df_clasters[["damage_grade"]]
X=df
scaler=MinMaxScaler()
Xt=X[:numx]
Xt=scaler.fit_transform(Xt)
Xt=Xt[:numx]
Y=Y[["damage_grade"]]
Y=Y[:numx]
X_train, X_test, y_train, y_test = train_test_split(Xt, Y, random_state=0)

In [63]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test,y_test)))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Accuracy of K-NN classifier on training set: 0.74
Accuracy of K-NN classifier on test set: 0.62


In [76]:
df

Unnamed: 0  ...  legal_ownership_status_v
0                0  ...                       1.0
1                1  ...                       1.0
2                2  ...                       1.0
3                3  ...                       1.0
4                4  ...                       1.0
...            ...  ...                       ...
260596      260596  ...                       1.0
260597      260597  ...                       1.0
260598      260598  ...                       1.0
260599      260599  ...                       1.0
260600      260600  ...                       1.0

[260601 rows x 57 columns]

In [64]:
df_testvalues

Unnamed: 0  ...  legal_ownership_status_v
0               0  ...                       1.0
1               1  ...                       1.0
2               2  ...                       1.0
3               3  ...                       1.0
4               4  ...                       1.0
...           ...  ...                       ...
86863       86863  ...                       0.0
86864       86864  ...                       1.0
86865       86865  ...                       1.0
86866       86866  ...                       0.0
86867       86867  ...                       1.0

[86868 rows x 78 columns]

In [65]:
df

Unnamed: 0  ...  legal_ownership_status_v
0                0  ...                       1.0
1                1  ...                       1.0
2                2  ...                       1.0
3                3  ...                       1.0
4                4  ...                       1.0
...            ...  ...                       ...
260596      260596  ...                       1.0
260597      260597  ...                       1.0
260598      260598  ...                       1.0
260599      260599  ...                       1.0
260600      260600  ...                       1.0

[260601 rows x 57 columns]

In [70]:
X_train

array([[0.86114419, 0.7       , 0.57393132, ..., 0.        , 0.        ,
        1.        ],
       [0.91928108, 0.36666667, 0.61878066, ..., 0.        , 1.        ,
        0.        ],
       [0.03370031, 0.26666667, 0.0287316 , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.38739443, 0.56666667, 0.61387526, ..., 0.        , 0.        ,
        1.        ],
       [0.39606724, 0.7       , 0.99929923, ..., 0.        , 0.        ,
        1.        ],
       [0.62062382, 0.2       , 0.47161878, ..., 0.        , 0.        ,
        1.        ]])

In [74]:
df_testvalues

Unnamed: 0  ...  legal_ownership_status_v
0               0  ...                       1.0
1               1  ...                       1.0
2               2  ...                       1.0
3               3  ...                       1.0
4               4  ...                       1.0
...           ...  ...                       ...
86863       86863  ...                       0.0
86864       86864  ...                       1.0
86865       86865  ...                       1.0
86866       86866  ...                       0.0
86867       86867  ...                       1.0

[86868 rows x 78 columns]

In [82]:
a=['geo_level_1_id', 'geo_level_2_id', 'count_floors_pre_eq', 'age',
       'area_percentage', 'height_percentage', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'count_families', 'has_secondary_use', 'has_secondary_use_agriculture',
       'has_secondary_use_hotel', 'has_secondary_use_rental',
       'has_secondary_use_institution', 'has_secondary_use_school',
       'has_secondary_use_industry', 'has_secondary_use_other',
       'land_surface_condition_t', 'land_surface_condition_o',
       'foundation_type_h', 'foundation_type_w', 'foundation_type_i',
       'foundation_type_r', 'foundation_type_u', 'roof_type_q', 'roof_type_n',
       'roof_type_x', 'ground_floor_type_z', 'ground_floor_type_v',
       'ground_floor_type_f', 'ground_floor_type_m', 'other_floor_type_q',
       'other_floor_type_s', 'other_floor_type_j', 'other_floor_type_x',
       'position_j', 'position_s', 'position_t', 'plan_configuration_c',
       'plan_configuration_s', 'plan_configuration_d', 'plan_configuration_a',
       'plan_configuration_u', 'plan_configuration_o',
       'legal_ownership_status_a', 'legal_ownership_status_w',
       'legal_ownership_status_v']

In [99]:
b=["geo_level_1_id","geo_level_2_id","count_floors_pre_eq","age","area_percentage","height_percentage","has_superstructure_adobe_mud","has_superstructure_mud_mortar_stone","has_superstructure_stone_flag","has_superstructure_cement_mortar_stone","has_superstructure_mud_mortar_brick","has_superstructure_cement_mortar_brick","has_superstructure_timber","has_superstructure_bamboo","has_superstructure_rc_non_engineered","has_superstructure_rc_engineered","has_superstructure_other","count_families","has_secondary_use","has_secondary_use_agriculture","has_secondary_use_hotel","has_secondary_use_rental","has_secondary_use_institution","has_secondary_use_school","has_secondary_use_industry","has_secondary_use_other","land_surface_condition_t","land_surface_condition_o","foundation_type_h","foundation_type_w","foundation_type_i","foundation_type_r","foundation_type_u","roof_type_q","roof_type_n","roof_type_x","ground_floor_type_z","ground_floor_type_v","ground_floor_type_f","ground_floor_type_m","other_floor_type_q","other_floor_type_s","other_floor_type_j","other_floor_type_x","position_j","position_s","position_t","plan_configuration_c","plan_configuration_s","plan_configuration_d","plan_configuration_a","plan_configuration_u","plan_configuration_o","legal_ownership_status_a","legal_ownership_status_w","legal_ownership_status_v"]

In [101]:
print(len(b))

56


In [88]:
df_testvalues

Unnamed: 0  ...  legal_ownership_status_v
0               0  ...                       1.0
1               1  ...                       1.0
2               2  ...                       1.0
3               3  ...                       1.0
4               4  ...                       1.0
...           ...  ...                       ...
86863       86863  ...                       0.0
86864       86864  ...                       1.0
86865       86865  ...                       1.0
86866       86866  ...                       0.0
86867       86867  ...                       1.0

[86868 rows x 78 columns]

In [89]:
a

['geo_level_1_id',
 'geo_level_2_id',
 'count_floors_pre_eq',
 'age',
 'area_percentage',
 'height_percentage',
 'has_superstructure_adobe_mud',
 'has_superstructure_mud_mortar_stone',
 'has_superstructure_stone_flag',
 'has_superstructure_cement_mortar_stone',
 'has_superstructure_mud_mortar_brick',
 'has_superstructure_cement_mortar_brick',
 'has_superstructure_timber',
 'has_superstructure_bamboo',
 'has_superstructure_rc_non_engineered',
 'has_superstructure_rc_engineered',
 'has_superstructure_other',
 'count_families',
 'has_secondary_use',
 'has_secondary_use_agriculture',
 'has_secondary_use_hotel',
 'has_secondary_use_rental',
 'has_secondary_use_institution',
 'has_secondary_use_school',
 'has_secondary_use_industry',
 'has_secondary_use_other',
 'land_surface_condition_t',
 'land_surface_condition_o',
 'foundation_type_h',
 'foundation_type_w',
 'foundation_type_i',
 'foundation_type_r',
 'foundation_type_u',
 'roof_type_q',
 'roof_type_n',
 'roof_type_x',
 'ground_floor_typ

In [102]:
df_testvalues[a]

geo_level_1_id  ...  legal_ownership_status_v
0                  17  ...                       1.0
1                   6  ...                       1.0
2                  22  ...                       1.0
3                  26  ...                       1.0
4                  17  ...                       1.0
...               ...  ...                       ...
86863               4  ...                       0.0
86864              10  ...                       1.0
86865              22  ...                       1.0
86866               6  ...                       0.0
86867              26  ...                       1.0

[86868 rows x 56 columns]

In [103]:

df_testvalues

Unnamed: 0  ...  legal_ownership_status_v
0               0  ...                       1.0
1               1  ...                       1.0
2               2  ...                       1.0
3               3  ...                       1.0
4               4  ...                       1.0
...           ...  ...                       ...
86863       86863  ...                       0.0
86864       86864  ...                       1.0
86865       86865  ...                       1.0
86866       86866  ...                       0.0
86867       86867  ...                       1.0

[86868 rows x 78 columns]

In [104]:
df_testvalues=scaler.fit_transform(df_testvalues)
Ypredikt=knn.predict(df_testvalues)


ValueError: ignored

In [68]:
Ypredikt

array([2, 2, 2, ..., 3, 2, 2])

In [45]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(lda.score(X_train, y_train)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(lda.score(X_test, y_test)))

Accuracy of LDA classifier on training set: 0.59
Accuracy of LDA classifier on test set: 0.59


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, y_test)))

Accuracy of GNB classifier on training set: 0.39
Accuracy of GNB classifier on test set: 0.38


/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [47]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of SVM classifier on training set: 0.61
Accuracy of SVM classifier on test set: 0.60


In [77]:
a=['geo_level_1_id', 'geo_level_2_id', 'count_floors_pre_eq', 'age',
       'area_percentage', 'height_percentage', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'count_families', 'has_secondary_use', 'has_secondary_use_agriculture',
       'has_secondary_use_hotel', 'has_secondary_use_rental',
       'has_secondary_use_institution', 'has_secondary_use_school',
       'has_secondary_use_industry', 'has_secondary_use_other',
       'land_surface_condition_t', 'land_surface_condition_o',
       'foundation_type_h', 'foundation_type_w', 'foundation_type_i',
       'foundation_type_r', 'foundation_type_u', 'roof_type_q', 'roof_type_n',
       'roof_type_x', 'ground_floor_type_z', 'ground_floor_type_v',
       'ground_floor_type_f', 'ground_floor_type_m', 'other_floor_type_q',
       'other_floor_type_s', 'other_floor_type_j', 'other_floor_type_x',
       'position_j', 'position_s', 'position_t', 'plan_configuration_c',
       'plan_configuration_s', 'plan_configuration_d', 'plan_configuration_a',
       'plan_configuration_u', 'plan_configuration_o',
       'legal_ownership_status_a', 'legal_ownership_status_w',
       'legal_ownership_status_v']

In [ ]:
X_test=

In [39]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 8 25  1]
 [ 8 92 36]
 [ 1 48 31]]
              precision    recall  f1-score   support

           1       0.47      0.24      0.31        34
           2       0.56      0.68      0.61       136
           3       0.46      0.39      0.42        80

    accuracy                           0.52       250
   macro avg       0.49      0.43      0.45       250
weighted avg       0.51      0.52      0.51       250



In [42]:
Y

damage_grade
0               3
1               2
2               3
3               2
4               3
..            ...
995             2
996             2
997             2
998             3
999             1

[1000 rows x 1 columns]