<a href="https://colab.research.google.com/github/sipocz/_earthQuake/blob/main/EarthQuaqe_Clustering_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
#EarthQuake
from google.colab import drive
drive.mount('/content/drive',force_remount=True)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import sweetviz as sw

#!pip install sweetviz
#import sweetviz as sw
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

Mounted at /content/drive


In [30]:
df=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/features_a.csv")
df_clasters=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/train_labels.csv")
df_testvalues=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/test_a.csv")

In [31]:
numx=260601
Y=df_clasters[["damage_grade"]]
X=df
scaler=MinMaxScaler()
Xt=X[:numx]
Xt=scaler.fit_transform(Xt)
Xt=Xt[:numx]
Y=Y[["damage_grade"]]
Y=Y[:numx]
X_train, X_test, y_train, y_test = train_test_split(Xt, Y, random_state=0)

heads=df.columns
print(len(heads))
print(len(df_testvalues.columns))
for i in df_testvalues.columns:
    if i not in heads:
        df_testvalues.drop(columns=[i], inplace=True)

print(len(df_testvalues.columns))

57
78
57


In [10]:
pcomponent=40
a=["p"+str(i) for i in range(pcomponent)]
a

['p0',
 'p1',
 'p2',
 'p3',
 'p4',
 'p5',
 'p6',
 'p7',
 'p8',
 'p9',
 'p10',
 'p11',
 'p12',
 'p13',
 'p14',
 'p15',
 'p16',
 'p17',
 'p18',
 'p19',
 'p20',
 'p21',
 'p22',
 'p23',
 'p24',
 'p25',
 'p26',
 'p27',
 'p28',
 'p29',
 'p30',
 'p31',
 'p32',
 'p33',
 'p34',
 'p35',
 'p36',
 'p37',
 'p38',
 'p39']

In [11]:
'''
# Menjünk át egy PCA transzformácoón
from sklearn.decomposition import PCA


pca = PCA(n_components=pcomponent)
principalComponents_X_train = pca.fit_transform(X_train)
principal_X_train_Df = pd.DataFrame(data = principalComponents_X_train, columns = a)

principalComponents_X_test= pca.transform(X_test)
principal_X_test_Df = pd.DataFrame(data = principalComponents_X_test, columns = a)
'''

In [18]:
'''
# Menjünk át egy LDA transzformácoón

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=pcomponent)
LDAComponents_X_train = lda.fit_transform(X_train,y_train)

LDAComponents_X_test= lda.transform(X_test)



'''

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:463: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(57, 3 - 1) = 2 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:469: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)


In [53]:
# NMF modell *************** n_components=25 : 70%
from sklearn.decomposition import NMF
nmf = NMF(n_components=40, init='random', random_state=0)

In [54]:
W = nmf.fit(X_train,y_train)
X_train_transformed= nmf.transform(X_train)
X_test_transformed= nmf.transform(X_test)


In [41]:
X_test_transformed

array([[0.25898956, 0.        ],
       [0.3010564 , 0.03982216],
       [0.29730266, 0.        ],
       ...,
       [0.30340904, 0.        ],
       [0.14816559, 0.58928361],
       [0.30000116, 0.        ]])

In [32]:
LDAComponents_X_test 


array([[ 0.69662199, -0.5754897 ],
       [ 0.23848898,  0.7038547 ],
       [ 0.49238022,  1.19374941],
       ...,
       [ 0.19210755, -1.01985554],
       [-2.51012629, -0.60427336],
       [ 0.45623244, -0.92992605]])

In [33]:
principal_X_test_Df.head()

p0        p1        p2  ...       p37       p38       p39
0 -0.671078 -0.233859 -0.000551  ... -0.008536  0.033766  0.006081
1 -0.590303 -0.201116  0.030018  ... -0.015386 -0.014958  0.006382
2 -0.608563 -0.198778  0.049022  ...  0.016889  0.086360  0.006516
3 -0.207597  1.147004  0.915387  ...  0.012993  0.067770  0.006260
4 -0.408145  1.102931 -0.137310  ... -0.013057 -0.035307  0.004139

[5 rows x 40 columns]

In [55]:
from xgboost import XGBClassifier  # 72.09
# max_depth=10 : 72.79857561664441



knn = XGBClassifier(verbosity=3,max_depth = 20)


[23:44:23] ======== Monitor: Learner ========
[23:44:23] GetGradient: 2.87956s, 100 calls @ 28795us
[23:44:23] PredictRaw: 0.118536s, 100 calls @ 1185us
[23:44:23] UpdateOneIter: 749.153s, 100 calls @ 7491525us
[23:44:23] ======== Monitor: GBTree ========
[23:44:23] BoostNewTrees: 730.345s, 100 calls @ 7303452us
[23:44:23] CommitModel: 15.8079s, 100 calls @ 158079us


In [ ]:
print("Fit Start--")
knn.fit(X_train_transformed, y_train)

print("Fit End--")


y_pred=knn.predict(X_test_transformed)
print("Prediction End--")

Fit Start--


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[23:44:35] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10722 extra nodes, 0 pruned nodes, max_depth=20
[23:44:39] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 25846 extra nodes, 0 pruned nodes, max_depth=20
[23:44:44] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 19954 extra nodes, 0 pruned nodes, max_depth=20
[23:44:48] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10892 extra nodes, 0 pruned nodes, max_depth=20
[23:44:52] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 25176 extra nodes, 0 pruned nodes, max_depth=20
[23:44:57] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 19952 extra nodes, 0 pruned nodes, max_depth=20
[23:45:01] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 11050 extra nodes, 0 pruned nodes, max_depth=20
[23:45:06] INFO: /workspace/src/tree/updater_prune.cc:74: tree prunin

In [43]:
LDAComponents_X_test

array([[ 0.69662199, -0.5754897 ],
       [ 0.23848898,  0.7038547 ],
       [ 0.49238022,  1.19374941],
       ...,
       [ 0.19210755, -1.01985554],
       [-2.51012629, -0.60427336],
       [ 0.45623244, -0.92992605]])

In [ ]:
print("Fit Start--")
knn.fit(LDAComponents_X_train , y_train)

print("Fit End--")


y_pred=knn.predict(LDAComponents_X_test)
print("Prediction End--")

In [ ]:
'''
print("Fit Start--")
knn.fit(principal_X_train_Df, y_train)

print("Fit End--")


y_pred=knn.predict(principal_X_test_Df)
print("Prediction End--")

'''


In [25]:
sum(y_pred)

141659

In [52]:
from sklearn.metrics import accuracy_score
accuracy =  accuracy_score(y_test, y_pred) * 100
print(f"Accuracy: {accuracy}")


Accuracy: 70.2015318260656


In [27]:
LDAComponents_Y= lda.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score
accuracy =  accuracy_score(y_test, LDAComponents_Y) * 100
print(f"Accuracy: {accuracy}")


Accuracy: 58.56548633175239


In [11]:
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
from sklearn.neural_network import MLPClassifier
#knn=MLPClassifier()
knn.fit(X_train, y_train)
print("Fit End--")
y_pred=knn.predict(X_test)
print("Prediction End--")

accuracy =  accuracy_score(y_test, y_pred) * 100
print(f"Accuracy: {accuracy}")


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


Fit End--
Prediction End--
Accuracy: 63.89846153846154


In [12]:
df_testvalues=scaler.fit_transform(df_testvalues)
Ypredikt=knn.predict(df_testvalues)


In [13]:
Ypredikt

array([3, 2, 2, ..., 2, 2, 2])

In [14]:
df_testo=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/test_a.csv")

In [15]:
df_testo.head()

Unnamed: 0  building_id  ...  legal_ownership_status_r  legal_ownership_status_v
0           0       300051  ...                       0.0                       1.0
1           1        99355  ...                       0.0                       1.0
2           2       890251  ...                       0.0                       1.0
3           3       745817  ...                       0.0                       1.0
4           4       421793  ...                       0.0                       1.0

[5 rows x 78 columns]

In [16]:
df_testBuilding=df_testo[["building_id"]]

In [17]:
df_testBuilding.head()

building_id
0       300051
1        99355
2       890251
3       745817
4       421793

In [18]:
df_out=pd.DataFrame(data=Ypredikt,columns=["damage_grade"], index=list(df_testBuilding["building_id"]),)
df_out.index.name="building_id"
df_out.head()
df_out.to_csv("/content/drive/My Drive/001_AI/_EarthQuake/submission_3_MLP.csv")

In [19]:
!head /content/drive/My Drive/001_AI/_EarthQuake/submission_2.csv

head: cannot open '/content/drive/My' for reading: No such file or directory
head: cannot open 'Drive/001_AI/_EarthQuake/submission_2.csv' for reading: No such file or directory


In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(lda.score(X_train, y_train)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(lda.score(X_test, y_test)))

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, y_test)))

In [ ]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

In [ ]:
a=['geo_level_1_id', 'geo_level_2_id', 'count_floors_pre_eq', 'age',
       'area_percentage', 'height_percentage', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'count_families', 'has_secondary_use', 'has_secondary_use_agriculture',
       'has_secondary_use_hotel', 'has_secondary_use_rental',
       'has_secondary_use_institution', 'has_secondary_use_school',
       'has_secondary_use_industry', 'has_secondary_use_other',
       'land_surface_condition_t', 'land_surface_condition_o',
       'foundation_type_h', 'foundation_type_w', 'foundation_type_i',
       'foundation_type_r', 'foundation_type_u', 'roof_type_q', 'roof_type_n',
       'roof_type_x', 'ground_floor_type_z', 'ground_floor_type_v',
       'ground_floor_type_f', 'ground_floor_type_m', 'other_floor_type_q',
       'other_floor_type_s', 'other_floor_type_j', 'other_floor_type_x',
       'position_j', 'position_s', 'position_t', 'plan_configuration_c',
       'plan_configuration_s', 'plan_configuration_d', 'plan_configuration_a',
       'plan_configuration_u', 'plan_configuration_o',
       'legal_ownership_status_a', 'legal_ownership_status_w',
       'legal_ownership_status_v']

In [ ]:
X_test=

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

In [ ]:
Y

In [19]:
'''
df=pd.read_csv("/content/drive/My Drive/001_AI/_EarthQuake/test_values.csv")
def checkvalues(columnname,key):
    print(f"{columnname} ellenőrzése !")
    numok=0
    numerr=0
    for i in df.index:
        if df.at[i,columnname] in key:
            #print(df.at[i,columnname])
            numok+=1
            pass
        else:
            numerr+=1
            print(df.at[i,columnname],end=", ")
    sumall=numok+numerr
    print(f"\n{sumall} mintából {numerr} db nem volt megfelelő")


def createcolumn(columnname,keys):
    for key in keys:
        df[keys[key]]=0.0
    for key in keys:
        for i in df.index:
            if df.at[i,columnname]==key:
                df.at[i,keys[key]]=1.0


def create_dict(idx,list):
    o={}
    for i in list:
        o[i]=idx+"_"+i
    return o

t=['n', 't', 'o']
columnname="land_surface_condition"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)

t= ['h', 'w', 'i', 'r', 'u']
columnname="foundation_type"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)

t=  ['q', 'n', 'x']
columnname="roof_type"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)

t=  ['z', 'v', 'f', 'm', 'x']
columnname="ground_floor_type"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)

t=   ['q', 's', 'j', 'x']
columnname="other_floor_type"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)

t=   ['j', 's', 't', 'o']
columnname="position"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)

t=   ['c', 's', 'f', 'd', 'm', 'a', 'q', 'u', 'n', 'o']
columnname="plan_configuration"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)


t=['a', 'w', 'r', 'v']
columnname="legal_ownership_status"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)


t=['a', 'w', 'r', 'v']
columnname="legal_ownership_status"
key=create_dict(columnname,t)

checkvalues(columnname,key)
createcolumn(columnname,key)




nlarge=list((ColListF+ColListA))
# ha összefűződik a 2 lista lehet, hogy benne van a SalePrice is. Az NAGYON nem jó
if "damage_grade" in nlarge[1:]:
    print("damage_grade a fedélzeten :-( ")


print(nlarge)
print(len(nlarge))


for i in df.columns:
    if i not in nlarge:
        df.drop(columns=[i], inplace=True)



df.head()

'''

land_surface_condition ellenőrzése !

86868 mintából 0 db nem volt megfelelő
foundation_type ellenőrzése !

86868 mintából 0 db nem volt megfelelő
roof_type ellenőrzése !

86868 mintából 0 db nem volt megfelelő
ground_floor_type ellenőrzése !

86868 mintából 0 db nem volt megfelelő
other_floor_type ellenőrzése !

86868 mintából 0 db nem volt megfelelő
position ellenőrzése !

86868 mintából 0 db nem volt megfelelő
plan_configuration ellenőrzése !

86868 mintából 0 db nem volt megfelelő
legal_ownership_status ellenőrzése !

86868 mintából 0 db nem volt megfelelő
legal_ownership_status ellenőrzése !

86868 mintából 0 db nem volt megfelelő


NameError: ignored

In [20]:
df.head()

building_id  ...  legal_ownership_status_v
0       300051  ...                       1.0
1        99355  ...                       1.0
2       890251  ...                       1.0
3       745817  ...                       1.0
4       421793  ...                       1.0

[5 rows x 77 columns]

In [21]:
df_testvalues

Unnamed: 0  ...  legal_ownership_status_v
0               0  ...                       1.0
1               1  ...                       1.0
2               2  ...                       1.0
3               3  ...                       1.0
4               4  ...                       1.0
...           ...  ...                       ...
86863       86863  ...                       0.0
86864       86864  ...                       1.0
86865       86865  ...                       1.0
86866       86866  ...                       0.0
86867       86867  ...                       1.0

[86868 rows x 78 columns]